### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by vondele**
@noobpwnftw these are the changes I need to get it to build. Fixes:

''
search.cpp: In function ‘size_t cURL_WriteFunc(void*, size_t, size_t, std::__cxx11::string*)’:
search.cpp:165:25: error: exception handling disabled, use -fexceptions to enable
  catch (std::bad_alloc &e)
                         ^
search.cpp: In member function ‘virtual void MainThread::search()’:
search.cpp:241:36: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
         if (g_szRecv.find("move:") >= 0)
             ~~~~~~~~~~~~~~~~~~~~~~~^~~~
search.cpp:243:59: error: cannot bind non-const lvalue reference of type ‘std::__cxx11::string& {aka std::__cxx11::basic_string<char>&}’ to an rvalue of type ‘std::__cxx11::basic_string<char>’
           bookMove = UCI::to_move(rootPos, g_szRecv.substr(5));
                                            ~~~~~~~~~~~~~~~^~~
In file included from search.cpp:37:0:
uci.h:76:6: note:   initializing argument 2 of ‘Move UCI::to_move(const Position&, std::__cxx11::string&)’
 Move to_move(const Position& pos, std::string& str);
      ^~~~~~~
''

### CODE REVIEW

**Comment by noobpwnftw** [comment]
Confirmed that it also works on Windows builds, thanks!

**Comment by vondele** [comment]
thanks. However, somewhat strange is that the moves returned by the query are 'strange' and change from call to call, e.g. b2b3 for startpos (reload a couple of times):

http://www.chessdb.cn/cdb.php?action=querybest&board=rnbqkbnr%2Fpppppppp%2F8%2F8%2F8%2F8%2FPPPPPPPP%2FRNBQKBNR%20w%20KQkq%20-%200%201

**Comment by noobpwnftw** [comment]
That's the intended behavior to introduce diversity:
https://github.com/noobpwnftw/chessdb/blob/e3bcc1ddf0826cab54a00d24d8e92ce47f312368/cdb.php#L1029-L1040

Changing `action=querybest` to `action=query` gives even wider range of moves.

It's a live book, there is a small cluster of workers developing the tree on-the-fly.

**Comment by vondele** [comment]
I see, I was assuming querybest to give the single bestmove.

**Pull request merged**
